export {default as Home} from './Home/Home';
export {default as College} from '../screens/CollegeScreen/Colloge';
export {default as Course} from './CourseScreen/Course';
export {default as Exam} from './ExamScreen/Exam';
export {default as Corporate} from './CorporateScreen/Corporate';
export {default as Practice} from './PracticeScreen/Practice';
export {default as MockTestList} from '../Components/Modules/Practice/MockTestList';  
export {default as Instrucation} from '../Components/Modules/Practice/Instrucation';  
export {default as MockTest} from '../Components/Modules/Practice/MockTest';  
export {default as MockTestActivity} from '../Components/Modules/Practice/MockTestActivity';  
export {default as MockTestScore} from '../Components/Modules/Practice/MockTestScore';  
export {default as MessageScreen} from '../screens/MessageScreen/MessageScreen';  
export {default as RequestLinks} from '../screens/RequestLinkScreen/RequestLinks';  
export {default as ChatScreen} from '../screens/ChatScreen/ChatScreen';  
export {default as CollegeInnerPage} from '../Components/Modules/College/CollegeInnerPage';  
export {default as EditProfile} from '../screens/EditProfile/EditProfile';  
export {default as SignupScreen} from '../screens/SignupScreen/SignupScreen';  
export {default as LoginScreen} from '../screens/LoginScreen/LoginScreen';  
export {default as OtpVerification} from '../screens/OtpScreen/OtpVerification'; 
 export {default as FilterUi} from '../Components/RepeatComponents/FilterUi'
 export {default as ExamFilter} from '../Components/Modules/Exams/Filter'
 export {default as CollegeFilter} from '../Components/Modules/College/Filter'
 export {default as Notification} from '../screens/Notification/Notification'
