export default {
    //ICONS
  IC_HOME: require('../assets/images/home.png'),
  IC_COLLEGE: require('../assets/images/college.png'),
  IC_EXAM: require('../assets/images/corporetion.png'),
  IC_MESSAGE: require('../assets/images/message.png'),
  IC_NOTIFICATION: require('../assets/images/notification.png'),
  IC_COURSE: require('../assets/images/course.png'),
  IC_CORPORETE: require('../assets/images/corporetion.png'),
  IC_MENU: require('../assets/images/menu.png'),
  IC_SEARCH: require('../assets/images/search.png'),
  IC_SETTING: require('../assets/images/filter.png'),
  IC_DOWN_ARROW: require('../assets/images/downArrow.png'),
  IC_Practice: require('../assets/images/practice.png'),
  IC_MAIN_MENU: require('../assets/images/mainMenu.png'),
  IC_Rectangle: require('../assets/images/Rectangle.png'),
  IC_SHARE: require('../assets/images/share.png'),
  IC_ADD_PEOPLE: require('../assets/images/addPople.png'),
  IC_LIKE: require('../assets/images/like.png'),
  IC_FILE_SAVE: require('../assets/images/fileSave.png'),
  IC_BOOK: require('../assets/images/book.png'),
  IC_LOCATION: require('../assets/images/location.png'),
  IC_ADDRATE: require('../assets/images/addrate.png'),
  IC_ATTACHMENT: require('../assets/images/attachment.png'),
  IC_COMMENTS: require('../assets/images/comments.png'),
  IC_STUDENT: require('../assets/images/graduateStudent.png'),
  IC_HOURS: require('../assets/images/hoursIcons.png'),
  IC_LIKE_CLLAPING: require('../assets/images/likeClaping.png'),
  IC_SHARE_POST: require('../assets/images/shareCountIcon.png'),
  IC_SEND: require('../assets/images/send.png'),
  IC_ADD_POST: require('../assets/images/post.png'),
  IC_ADD_FROM_GALLERY: require('../assets/images/gallery.png'),
  IC_CLOSE: require('../assets/images/close.png'),
  IC_REACTION: require('../assets/images/review.png'),
  IC_CIRCLE_QUESTION: require('../assets/images/question-circle.png'),
  IC_Right_ARROW: require('../assets/images/rightArrow.png'),
  IC_VIEWS: require('../assets/images/views.png'),
  IC_DOWNLOAD: require('../assets/images/dowmload.png'),
  IC_DOWNLOADSymbols: require('../assets/images/downloadSymbol.png'),
  IC_LIKESymbols: require('../assets/images/likesSymbols.png'),
  IC_SAVE: require('../assets/images/save.png'),
  IC_TIME: require('../assets/images/time.png'),
  IC_QUESTION: require('../assets/images/question.png'),
  IC_MARKS: require('../assets/images/marks.png'),
  IC_TIMER_PAUSE: require('../assets/images/pauseTimer.png'),
  IC_UNCHECK: require('../assets/images/unCheck.png'),
  IC_CHECK: require('../assets/images/check.png'),
  IC_REATTEMPT: require('../assets/images/reAttempt.png'),
  IC_SKIP_QUESTION: require('../assets/images/skipQuestion.png'),
  IC_WRONG_QUESTION: require('../assets/images/wrongQuestion.png'),
  IC_CORRECT_QUESTION: require('../assets/images/correctQuestion.png'),

  // profile image
  Profile: require('../assets/images/profile.png'),
  COLLEGE_IMAGE: require('../assets/images/collegeProfile.png'),
  STATUS_PERSON_IMAGE: require('../assets/images/person.jpg'),
  Other_PROFILE: require('../assets/images/otherProfile.png'),
  DEMO_PROGRESS: require('../assets/images/demoProgress.png'),

};
